### PR TITLE
Refactor code

### LINKED ISSUE #24: Framework#: Refactor code based on usage
Need to determine what methods are/aren't being used and refactor. Right now we have search_api_controller and methods within google_search that aren't being used

### PR DESCRIPTION
**Pull request by mtkumar123**
Merging RefactorCode branch which contains only the necessary code into main.

### CODE REVIEW

**Comment by kingan1** [comment]
Code looks good, failure on test_get_people_also_ask_links_data_check . Need to open an issue to fix it.

**Comment by rakeshavm** [comment]
Can be pushed to main. Looks good.

**Comment by ashwindasr** [comment]
Looks good.

**Comment by kingan1** [comment]
Code merged due to group consensus. Issue will be created to fix failing tests

**Pull request merged**
